version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
    container_name: elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - xpack.license.self_generated.type=trial
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:8.8.2
    container_name: kibana
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
      - 5601:5601
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  hyderator:
    image: 3pillar/essm
    container_name: hyderator
    depends_on:
      - elasticsearch
    volumes:
      - ./data:/app/data
    environment:
      - es_host=http://elasticsearch:9200
    restart: on-failure
    command: python hydrate_with_marco_dataset.py

  streamlit:
    image: 3pillar/pensieve
    container_name: streamlit
    depends_on:
      - elasticsearch
    volumes:
      - ./data:/app/data
    environment:
      - es_host=http://elasticsearch:9200
    ports:
      - 8501:8501
    restart: on-failure
    command: streamlit run app.py

volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local
